### ISSUE TITLE
Embedding fails - Not able to add documents

### ISSUE THREAD

**Issue by julian-dymek** [weaviate/Verba#205] opened 2024-05-27 03:53 UTC
When I try to add documents, I get the error down below.
I installed Verba in a conda environment with pip. I am able to run llama3 and gpt4, but am not able to add documents.

(INFO) Importing...
(ERROR) Delete object! Unexpected status code: 500, with response body: {'error': [{'message': 'could not delete object from vector repo: delete from index "verba_config": delete local object: shard="x8U9x6HOhDpr": store is read-only'}]}.

**Comment by donadelden** [comment] 2024-05-27 09:47
I just got the same error, solved by running Verba from a new directory with permissions 777. Something like:
```
mkdir test
cp .env test
cd test
chmod 777 .
verba run
```

**Comment by thomashacker** [comment] 2024-05-27 11:19
Interesting! Thanks for the issue, we'll have a look

**Comment by jamesoflol** [comment] 2024-05-31 06:57
Same.

I'm not sure if it's related, but I'm also getting this message: {"action":"read_disk_use","level":"warning","msg":"disk usage currently at 86.36%, threshold set to 80.00%"

**Comment by lucasrocha7111** [comment] 2024-06-04 15:48
Same here issue here.

Apple M2 Pro
MacOS Sonoma 14.5 
Python 3.12.3

**Comment by lucasrocha7111** [comment] 2024-06-04 17:35
One way to solve it is run using Docker

**Comment by samaphp** [comment] 2024-08-03 14:18
I have confirmed that this issue is affected by several factors:

- **Project Folder Permissions:** Ensure that the repository folder has the proper permissions before running verba start. Incorrect permissions can cause various issues.
- **Available Disk Space:** Ensure that your disk space is below the threshold. If the disk is nearly full, the system may automatically switch to a read-only mode, which can lead to errors.
- **Environment Variables:** Make sure that the environment variables OLLAMA_URL and OLLAMA_MODEL are set. You can find an example of these in the .env.example file.

Here are the errors I encountered:
- `flush halted due to shard READONLY status`
- `could not delete object from vector repo: delete from index "verba_config": delete local object: shard="ifrwh8eZAyOJ": store is read-only`
- `update vector: API Key: no api key found neither in request header: X-Openai-Api-Key nor in environment variable`

The "store is read-only" error was misleading in my case because my disk was 98% full. and I was getting this error: `Set READONLY, disk usage currently at 93.20%, threshold set to 90.00%`
You can check the actual disk availability using the command df -h. After reducing the disk usage to below the threshold, everything worked fine:

I hope this helps in resolving the issue.

**Closed** 2024-09-03 13:07 UTC
Labels: investigating
