### ISSUE TITLE
load_data API throw "NoneType' object has no attribute 'tokenize'"

### ISSUE THREAD

**Issue by dhara-seaflux** [weaviate/Verba#64] opened 2023-11-26 10:36 UTC
http://0.0.0.0:8000/api/load_data

Request payload:
{
    "reader": "SimpleReader",
    "chunker": "TokenChunker",
    "embedder": "MiniLMEmbedder",
    "fileBytes": [
        "T3JnYW5pemF0aW9uIE5hbWU6IFJhaGFzYWsgUmVzZWFyY2ggUGFwZXJzCgpEYXRlOiBOb3ZlbWJlciA2LCAyMDIzCgpSZXNlYXJjaCBUb3BpYzogRXhwbG9yaW5nIFN1c3RhaW5hYmxlIEVuZXJneSBTb2x1dGlvbnMgZm9yIFVyYmFuIEVudmlyb25tZW50cwoKVGVzdCBEYXRhIFNldDogU2NpZW50aWZpYyBSZXNlYXJjaCBQYXBlcgoKVGl0bGU6IFRvd2FyZHMgQ2FyYm9uIE5ldXRyYWxpdHk6IEludGVncmF0aW5nIFJlbmV3YWJsZSBFbmVyZ3kgU291cmNlcyBpbiBVcmJhbiBJbmZyYXN0cnVjdHVyZQoKQXV0aG9yczogRHIuIEVtaWx5IEMuIFBhcmtlciwgRHIuIE1pY2hhZWwgSi4gQWRhbXMsIERyLiBTb3BoaWEgTC4gQ2hlbgoKQWJzdHJhY3Q6IFRoaXMgY29tcHJlaGVuc2l2ZSBzY2llbnRpZmljIHJlc2VhcmNoIHBhcGVyIGludmVzdGlnYXRlcyB0aGUgaW50ZWdyYXRpb24gb2YgcmVuZXdhYmxlIGVuZXJneSBzb3VyY2VzIGludG8gdXJiYW4gaW5mcmFzdHJ1Y3R1cmUgdG8gYWNoaWV2ZSBjYXJib24gbmV1dHJhbGl0eS4gVGhlIHN0dWR5IGFuYWx5emVzIHZhcmlvdXMgc3VzdGFpbmFibGUgZW5lcmd5IHNvbHV0aW9ucywgaW5jbHVkaW5nIHNvbGFyIHBvd2VyLCB3aW5kIGVuZXJneSwgYW5kIGh5ZHJvZWxlY3RyaWNpdHksIGFuZCBleHBsb3JlcyB0aGVpciBpbXBsZW1lbnRhdGlvbiBpbiBkZW5zZWx5IHBvcHVsYXRlZCB1cmJhbiBlbnZpcm9ubWVudHMuIFRoZSBwYXBlciBkaXNjdXNzZXMgdGhlIGNoYWxsZW5nZXMsIGJlbmVmaXRzLCBhbmQgcG90ZW50aWFsIGltcGFjdCBvbiByZWR1Y2luZyBjYXJib24gZW1pc3Npb25zIGluIGNpdGllcy4KClB1Ymxpc2hlZCBEYXRlOiBPY3RvYmVyIDI1LCAyMDIzCgpTdW1tYXJ5OgpJbiB0aGlzIGdyb3VuZGJyZWFraW5nIHJlc2VhcmNoIHBhcGVyLCB0aGUgdGVhbSBvZiBleHBlcnRzIGF0IFJhaGFzYWsgUmVzZWFyY2ggUGFwZXJzLCBsZWQgYnkgRHIuIEVtaWx5IEMuIFBhcmtlciwgZGVsdmVzIGRlZXAgaW50byB0aGUgcmVhbG0gb2Ygc3VzdGFpbmFibGUgZW5lcmd5IHNvbHV0aW9ucyBmb3IgdXJiYW4gZW52aXJvbm1lbnRzLiBUaGUgcGFwZXIgcHJvdmlkZXMgYW4gaW4tZGVwdGggYW5hbHlzaXMgb2YgdGhlIGNoYWxsZW5nZXMgZmFjZWQgYnkgbW9kZXJuIGNpdGllcyBpbiBtaXRpZ2F0aW5nIHRoZSBlZmZlY3RzIG9mIGNsaW1hdGUgY2hhbmdlLiBCeSBmb2N1c2luZyBvbiByZW5ld2FibGUgZW5lcmd5IHNvdXJjZXMgc3VjaCBhcyBzb2xhciwgd2luZCwgYW5kIGh5ZHJvZWxlY3RyaWMgcG93ZXIsIHRoZSBhdXRob3JzIHByZXNlbnQgaW5ub3ZhdGl2ZSBzdHJhdGVnaWVzIHRvIHRyYW5zZm9ybSB1cmJhbiBsYW5kc2NhcGVzIGludG8gZW52aXJvbm1lbnRhbGx5IGZyaWVuZGx5IGh1YnMuCgpUaGUgcmVzZWFyY2ggcGFwZXIgbWV0aWN1bG91c2x5IGV4YW1pbmVzIGNhc2Ugc3R1ZGllcyBmcm9tIGVjby1jb25zY2lvdXMgY2l0aWVzIHdvcmxkd2lkZSwgc2hvd2Nhc2luZyBzdWNjZXNzZnVsIGltcGxlbWVudGF0aW9ucyBvZiByZW5ld2FibGUgZW5lcmd5IHRlY2hub2xvZ2llcy4gSXQgZGlzY3Vzc2VzIHRoZSBlY29ub21pYyB2aWFiaWxpdHksIGVudmlyb25tZW50YWwgaW1wYWN0LCBhbmQgc29jaWV0YWwgYmVuZWZpdHMgb2YgdHJhbnNpdGlvbmluZyBmcm9tIGZvc3NpbCBmdWVscyB0byByZW5ld2FibGUgc291cmNlcy4gVGhlIGF1dGhvcnMgZW1waGFzaXplIHRoZSBpbXBvcnRhbmNlIG9mIHBvbGljeSBpbnRlcnZlbnRpb25zLCB0ZWNobm9sb2dpY2FsIGFkdmFuY2VtZW50cywgYW5kIGNvbW11bml0eSBlbmdhZ2VtZW50IGluIGZvc3RlcmluZyBhIHN1c3RhaW5hYmxlIGVuZXJneSB0cmFuc2l0aW9uLgoKQWRkaXRpb25hbGx5LCB0aGUgcGFwZXIgZXhwbG9yZXMgdGhlIGludGVncmF0aW9uIG9mIHNtYXJ0IGdyaWQgc3lzdGVtcywgZW5lcmd5IHN0b3JhZ2Ugc29sdXRpb25zLCBhbmQgYWR2YW5jZWQgbW9uaXRvcmluZyB0ZWNobmlxdWVzIHRvIG9wdGltaXplIHRoZSB1dGlsaXphdGlvbiBvZiByZW5ld2FibGUgZW5lcmd5IGluIHVyYmFuIGFyZWFzLiBCeSBhZGRyZXNzaW5nIGJvdGggdGVjaG5pY2FsIGFuZCBzb2NpZXRhbCBhc3BlY3RzLCB0aGUgcmVzZWFyY2ggcGFwZXIgb2ZmZXJzIGEgaG9saXN0aWMgYXBwcm9hY2ggdG8gY3JlYXRpbmcgZW52aXJvbm1lbnRhbGx5IHN1c3RhaW5hYmxlIGNpdGllcy4KCkZ1dHVyZSBJbXBsaWNhdGlvbnM6ClRoaXMgcmVzZWFyY2ggcGFwZXIgc2VydmVzIGFzIGEgZm91bmRhdGlvbmFsIHJlc291cmNlIGZvciBwb2xpY3ltYWtlcnMsIHVyYmFuIHBsYW5uZXJzLCBhbmQgZW52aXJvbm1lbnRhbGlzdHMgc3RyaXZpbmcgdG8gY3JlYXRlIGdyZWVuZXIgY2l0aWVzLiBUaGUgZmluZGluZ3MgYW5kIHJlY29tbWVuZGF0aW9ucyBwcm92aWRlIHZhbHVhYmxlIGluc2lnaHRzIGludG8gdGhlIHByYWN0aWNhbCBpbXBsZW1lbnRhdGlvbiBvZiByZW5ld2FibGUgZW5lcmd5IHNvbHV0aW9ucywgcGF2aW5nIHRoZSB3YXkgZm9yIGNhcmJvbi1uZXV0cmFsIHVyYmFuIGVudmlyb25tZW50cy4gVGhlIHJlc2VhcmNoIGNvbnRyaWJ1dGVzIHNpZ25pZmljYW50bHkgdG8gdGhlIGdsb2JhbCBkaXNjb3Vyc2Ugb24gc3VzdGFpbmFibGUgZGV2ZWxvcG1lbnQsIG9mZmVyaW5nIHRhbmdpYmxlIHNvbHV0aW9ucyB0byBjb21iYXQgY2xpbWF0ZSBjaGFuZ2UgYW5kIGVuc3VyZSBhIG1vcmUgc3VzdGFpbmFibGUgZnV0dXJlIGZvciBnZW5lcmF0aW9ucyB0byBjb21l"
    ],
    "fileNames": [
        "data.txt"
    ],
    "filePath": "",
    "document_type": "Documentation",
    "chunkUnits": 250,
    "chunkOverlap": 50
}

Response:
{
    "status": "400",
    "status_msg": "'NoneType' object has no attribute 'tokenize'"
}

**Comment by cam-barts** [comment] 2023-11-27 09:00
Duplicate of #53

**Comment by thomashacker** [comment] 2023-11-28 17:15
Interesting! Will look into it, thanks!

**Comment by thomashacker** [comment] 2024-05-15 17:32
Should be fixed with the newest release v1.0.0

**Closed by thomashacker** 2024-05-15 17:32 UTC
Labels: bug
