### ISSUE TITLE
repeating the answer to the older questions in the chat

### ISSUE THREAD

**Issue by amihos** [weaviate/Verba#193] opened 2024-05-23 11:29 UTC
## Description
verba keeps responding to older messages in the chat, ignoring newer ones

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
start a chat, ask one question, then move to the next question

## Additional context

![image](https://github.com/weaviate/Verba/assets/35190548/2f6d0c51-2fd0-42ec-a12d-73a4c6e1d973)

**Comment by amihos** [comment] 2024-05-23 19:54
ollamaembeder

**Comment by thomashacker** [comment] 2024-05-27 11:23
What specific Ollama Model are you using? Might be that the issue is related to the model you're using

**Comment by amihos** [comment] 2024-05-28 10:34
llama 3

**Comment by thomashacker** [comment] 2024-05-31 11:32
Have you tried other models as well?

**Comment by mike-mathieu** [comment] 2024-08-14 19:52
This is happening to me as well. Using Ollama and OllamaImbedder. Once I turned off chat caching it seems to have stopped.

**Comment by thomashacker** [comment] 2024-09-03 12:50
Should be fixed in the latest release! 😄

**Closed by thomashacker** 2024-09-03 12:50 UTC
Labels: investigating
