### ISSUE TITLE
Error when importing larger PDF files

### ISSUE THREAD

**Issue by duob-ai** [weaviate/Verba#50] opened 2023-11-22 20:46 UTC
When trying to import larger PDF files (tested with upwards of 20 pages) using ADAEmbedder I'm seeing the following error in the front end and in the console.

However the embeddings somehow seem to be generated since asking questions for that context works. But the uploaded document isn't showing in the frontend under the documents section.

<img width="1302" alt="frontend" src="https://github.com/weaviate/Verba/assets/141818514/45d1ce2b-4b54-4ad4-9eb8-7eb6a184574c">

<img width="749" alt="console" src="https://github.com/weaviate/Verba/assets/141818514/936436f5-5b76-4cfc-baca-c0520b0fc5d4">

**Comment by thomashacker** [comment] 2023-11-24 13:01
Interesting! Thanks for the issue. It looks like the chunks are too big for OpenAI's ADA model (max 8192 tokens, but somehow one chunks seems to be 23941 tokens). What are your chunking settings?

**Comment by cam-barts** [comment] 2023-11-24 20:30
@thomashacker I opened #55 which ended up being duplicative of the issue here. I added some of my investigation info in that issue, but tldr the issue isn't in the chunks, its in the document upload itself *before* the chunking can occur.

**Comment by r0mdau** [comment] 2023-11-30 03:19
I encounter the same problem when starting Verba in a virtualenv with `verba start` and connecting to a weaviate instance running in docker.

No problem when using the weaviate embedded.

**Comment by thomashacker** [comment] 2023-12-05 10:25
Thanks everyone, I found the issue! The Docker configuration was set to automatically use the `openai-vectorizer` module, also for Documents, which was not intended. I committed the fix to the main branch 🚀 It should work now with larger documents

**Closed by thomashacker** 2023-12-05 10:25 UTC
Labels: bug

**Comment by micuentadecasa** [comment] 2023-12-07 07:39
> Thanks everyone, I found the issue! The Docker configuration was set to automatically use the `openai-vectorizer` module, also for Documents, which was not intended. I committed the fix to the main branch 🚀 It should work now with larger documents

Now it works for me, I had to clean all volumes, images, etc, and then a fresh environment and the new code did the trick.

**Comment by thomashacker** [comment] 2023-12-07 10:59
That's great to hear!
