### ISSUE TITLE
Embedder TokenChunker not found.

### ISSUE THREAD

**Issue by provVladBurlik** [weaviate/Verba#238] opened 2024-07-03 19:12 UTC
## Description
When following the instructions for azure open AI server starts, but when trying to add document - server show the message in the subject.

## Is this a bug or a feature?
- [ x] Bug
- [ ] Feature

## Steps to Reproduce
- start server
- start web client
- press add document and observe the logs on the server side  

## Additional context
Azure open AI
ubuntu 20.04 virtenv

**Comment by silicongarage** [comment] 2024-07-04 02:15
I'm getting the same error, but with different OS/setup.   
Docker container on Macbook Apple Silicon with Ollama server running on host.

When I click on "Add Documents" the web client errors with the following message:
`Application error: a client-side exception has occurred (see the browser console for more information).`

Checking the Docker server logs shows:
`Embedder TokenChunker not found`

**Comment by wythedee** [comment] 2024-07-04 10:01
Same problem. Used pip install to setup verba, went straightly to the web page and clicked on RAG and the same error occurs:`Application error: a client-side exception has occurred (see the browser console for more information).`
Wonder what did I miss.
Also I wanted to know if it is possible to set the ollama_url to a outer url but not local. That endpoint should owns the same service as ollama does. plz help!

**Comment by thomashacker** [comment] 2024-07-04 12:40
Thanks for the issue! This seems definitely like a bug.
What console message are you receiving from the frontend when `client-side exception` occurs?
Do any other errors occur?

Make sure that you install Verba in a clean environment to prevent dependency issues.

**Comment by provVladBurlik** [comment] 2024-07-04 15:44
I've added additional traces: 
![image](https://github.com/weaviate/Verba/assets/93543976/834db4e4-9123-45dc-99c6-0f5ab9d19d55)

**Comment by FlipinFlop** [comment] 2024-07-04 17:09
Same error

**Comment by provVladBurlik** [comment] 2024-07-04 17:11
> Thanks for the issue! This seems definitely like a bug. What console message are you receiving from the frontend when `client-side exception` occurs? Do any other errors occur?
> 
> Make sure that you install Verba in a clean environment to prevent dependency issues.

Installed in new virt env - as per instructions

**Comment by silicongarage** [comment] 2024-07-04 18:58
Looks like a change to managers.py was made two days ago.   I changed it back to the original and now the web page doesn't crash.  Ha, but now have a new problem with chunks not being found.

<img width="538" alt="Screenshot 2024-07-04 at 1 55 43 PM" src="https://github.com/weaviate/Verba/assets/35607907/5abcce26-533b-4238-9ff6-659f9a0c404a">

**Comment by provVladBurlik** [comment] 2024-07-04 22:50
I am using azure openai - does this work too?

**Comment by silicongarage** [comment] 2024-07-04 23:31
The main problem appears to be the change in _components/managers.py  so that's probably all you need. 
I had additional problems (masked by this) in my Ollama local LLM setup.

**Comment by thomashacker** [comment] 2024-07-07 09:33
Great catch! The `self.selected_embedder` variable had the wrong component name. 
Thanks a lot for debugging! Will be fixed and pushed asap

**Comment by thomashacker** [comment] 2024-07-07 09:37
Fixed and pushed, let me know if the error still persists

**Comment by shanumas** [comment] 2024-07-07 09:49
@thomashacker   Still the same.  But this one works:

![image](https://github.com/weaviate/Verba/assets/34864140/e07f8d22-3186-4b54-b917-a28b8b9a6d25)

**Comment by mamscience** [comment] 2024-07-18 13:06
@thomashacker the root cause of the error is a faulty configuration file which is stored in Weaviate Embedded.

In util.py, the manager sets the embedder (line 127), which it retrieves from the config file stored in the Weaviate database.
In this config file, TokenChunker is accidentally set to default 'selected', which util.py retrieves and manager doesn't like because TokenChunker is not a Embedder.

I hard coded the fix by adding CohereEmbedder here instead
util.py line 126/127
```
#manager.embedder_manager.set_embedder(config.get("Embedder", {}).get("selected", "")) #bug here
manager.embedder_manager.set_embedder("CohereEmbedder")
```

My suggestion would be is to add a json file with the standard config from which the application loads in the database. Took some time to retrieve the config file (which also was not valid JSON btw)

Thanks for your hard work.

**Comment by thomashacker** [comment] 2024-07-18 20:55
I agree, there's a lot of room for improvement for the configuration settings. When an invalid config is saved, the errors will most likely still persist. As workaround, you can reset the configuration file over the frontend. 

I'll add config validation in the coming update to avoid these issue in the future. Thanks a lot for the feedback 🚀

**Comment by shanumas** [comment] 2024-07-18 21:00
NO, all works well now.

**Closed** 2024-07-19 07:41 UTC
Labels: bug

**Comment by mamscience** [comment] 2024-07-21 22:08
@thomashacker absolutely my bad, just found the config-file in the root of the project.

So to solve this bug, one should go to the config-file and find the Embedder-attribute and got to the las key-pair and set selected from 'TokenChunker' to your favorite embedder.
`
